#-------------------------------------------------------------------------------
# Copyright (c) 2013 National ICT Australia Limited (NICTA).
# This software may be used and distributed solely under the terms of the MIT license (License).
# You should find a copy of the License in LICENSE.TXT or at http://opensource.org/licenses/MIT.
# By downloading or using this software you accept the terms and the liability disclaimer in the License.
#-------------------------------------------------------------------------------
#source "http://rubygems.org"

# Specify your gem's dependencies in omf_web.gemspec
#gemspec

git 'git://github.com/mytestbed/omf.git' do
  gem 'omf_common'
  gem 'omf_rc'  
end
  
gem 'oml4r', :git => 'git://github.com/mytestbed/oml4r.git'
#gem 'thread', :git => 'git://github.com/maxott/ruby-thread.git'
gem 'omf_common', 'git://github.com/mytestbed/omf.git'
gem 'omf_rc', 'git://github.com/mytestbed/omf.git'
