#!/bin/bash
# 
# Start the OMF resource controller
# 

CONFIG_FILE=/etc/omf_rc/cloud_node.yaml
RVM_VERSION=ruby-1.9.3-p374@omf

source /home/ubuntu/.rvm/environments/${RVM_VERSION}
ruby -romf_rc_cloud_node -e just_doit -- -c ${CONFIG_FILE} -m production $*
